--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/TitaniumLB6571/TitanCommandSpy
build-by-default: true
branches:
- master
projects:
  TitanCommandSpy:
    path: ""
    icon: "icon.png"
...
