name: CommandSpy
main: TitaniumLB\CommandSpy\Main
version: 1.0.5
api: 5.0.0
author: TitaniumLB
description: Cool Commandspy by Titanium

permissions:
  commandspy.cmd:
    default: op

  commandspy.cmd.list:
    default: op

  commandspy.cmd.target:
    default: op